USE AdventureWork_DW;

INSERT INTO FACT_SALES (
    PRODUCT_KEY,
    CUSTOMER_KEY,
    REGION_KEY,
    DATE_KEY,
    SALES_VOLUMES,
    SHIPPED_UNITS
)
SELECT
    P.PRODUCT_KEY
    , C.CUSTOMER_KEY
    , R.REGION_KEY
    , T.DATE_KEY
    , SH.TOTALDUE AS SALES_VOLUMES
    , SUM(SD.ORDERQTY) AS SHIPPED_UNITS
FROM ADVENTUREWORKS2017.SALES.SALESORDERHEADER SH
INNER JOIN ADVENTUREWORKS2017.SALES.SALESORDERDETAIL SD
    ON SH.SALESORDERID = SD.SALESORDERID
INNER JOIN DBO.DIM_CUSTOMER C
    ON SH.CUSTOMERID = C.CUSTOMER_ID
INNER JOIN DBO.DIM_REGION R
    ON SH.TERRITORYID = R.REGION_ID
INNER JOIN DBO.DIM_PRODUCT P
    ON SD.PRODUCTID = P.PRODUCT_ID
INNER JOIN DBO.DIM_DATE T
    ON SH.ORDERDATE = T.CALENDAR_DATE
GROUP BY
    P.PRODUCT_KEY
    , C.CUSTOMER_KEY
    , R.REGION_KEY
    , T.DATE_KEY
    , SH.TOTALDUE
