-- DATABASE: SALE
USE SALE
GO

CREATE TABLE DIM_PRODUCT (
    PRODUCT_KEY     INT NOT NULL
    , PRODUCT_CODE      VARCHAR(10)
    , NAME      VARCHAR(30)
    , DESCRIPTION VARCHAR(100)
    , TITLE VARCHAR(100)
    , ARTIST VARCHAR(100)
    , PRODUCT_TYPE VARCHAR(20)
    , PRODUCT_CATEGORY VARCHAR(30)
    , MEDIA VARCHAR(25)
    , UNIT_PRICE MONEY
    , UNIT_COST MONEY
    , STATUS VARCHAR(15)
    , SORCE_SYSTEM_CODE TINYINT
    , CREATE_TIMESTAMP DATETIME
    , UPDATE_TIMESTAMP DATETIME
    , CONSTRAINT PK_DIM_PRODUCT
    PRIMARY KEY CLUSTERED (PRODUCT_KEY)
)
GO

CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY        INT NOT NULL
    , CUSTIOMER_ID      VARCHAR(10)
    , ACCOUNT_NUMBER        INT
    , CUSTOMER_TYPE     CHAR(1)
    , NAME      VARCHAR(100)
    , GENDER        CHAR(1)
    , EMAIL_ADDRESS     VARCHAR(200)
    , DATE_OF_BIRTH     DATETIME
    , ADDRESS       VARCHAR(50)
    , CITY      VARCHAR(50)
    , STATE     VARCHAR(40)
    , ZIPCODE       VARCHAR(10)
    , COUNTRY       VARCHAR(50)
    , PHONE_NUMBER      VARCHAR(20)
    , OCCAUPATION       VARCHAR(50)
    , DATE_REGRISTERED      DATETIME
    , STATUS        VARCHAR(10)
    , EFFECTIVE_TIMESTAMP       DATETIME
    , EXPIRY_TIMESTAMP      DATETIME
    , IS_CURRENT        TINYINT
    , SOURCE_SYSTEM_CODE        TINYINT
    , CREATE_TIMESTAMP      DATETIME
    , UPDATE_TIMESTAMP      DATETIME
    , CONSTRAINT PK_DIM_CUSTOMER
    PRIMARY KEY CLUSTERED (CUSTOMER_KEY)
)
GO

